In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from random import randint

In [2]:
corpus = ['king is a strong man', 
          'queen is a wise woman', 
          'boy is a young man',
          'girl is a young woman',
          'prince is a young king',
          'princess is a young queen',
          'man is strong', 
          'woman is pretty',
          'prince is a boy will be king',
          'princess is a girl will be queen']

In [3]:
def remove_ents(line):
    line = line.replace('\n', '')
    return line

In [4]:
def read_input(input_file):
    with open(input_file) as f:
        for i, line in enumerate(f):
            if (i % 100 == 0):
                print(f"{i} lines read")
                
            if (i == 15000):
                break

            yield remove_ents(line).strip()
            
corpus = list(read_input("tweets.txt"))

0 lines read
100 lines read
200 lines read
300 lines read
400 lines read
500 lines read
600 lines read
700 lines read
800 lines read
900 lines read
1000 lines read
1100 lines read
1200 lines read
1300 lines read
1400 lines read
1500 lines read
1600 lines read
1700 lines read
1800 lines read
1900 lines read
2000 lines read
2100 lines read
2200 lines read
2300 lines read
2400 lines read
2500 lines read
2600 lines read
2700 lines read
2800 lines read
2900 lines read
3000 lines read
3100 lines read
3200 lines read
3300 lines read
3400 lines read
3500 lines read
3600 lines read
3700 lines read
3800 lines read
3900 lines read
4000 lines read
4100 lines read
4200 lines read
4300 lines read
4400 lines read
4500 lines read
4600 lines read
4700 lines read
4800 lines read
4900 lines read
5000 lines read
5100 lines read
5200 lines read
5300 lines read
5400 lines read
5500 lines read
5600 lines read
5700 lines read
5800 lines read
5900 lines read
6000 lines read
6100 lines read
6200 lines read
6300

In [5]:
print(corpus[0:50])

['to all the armys who were voting nonstop since yesterday thank you so much for your hard work rt quote', 'me when a d song plays on public', 'minutes your last votes about  k replies on army this is our countdown', 'forget well be trending the hashtag at am kst when the music video drops', 'theres about an hour left for voting keep using the tags', 'its been a crucial week for chemocentryx inc heres what analysts have to say', 'under the not here', 'please let us do the job and we are able', 'what we want to ask exol in what ways does exo inspires and with the hashtag', 'news channels not covering live what a shame', 'ellen meets a yearold geography expert via this is is funny but intelligent you should watch this', 'bts always breaks the status', 'the nick gee', 'thank you armys for voting remember that there is round  of', 'jongin hyung did you his you dont i didnt even know it was a', 'addiction party in the sky mv teaser', 'we want proof from mamta from where illegal bangladeshi 

In [6]:
def remove_stop_words(corpus):
    stop_words = ["is", "a", "will", "be", "but", "the", "and", "or"]
    results = []
    for text in corpus:
        tmp = text.split(' ')
        for stop_word in stop_words:
            if stop_word in tmp:
                tmp.remove(stop_word)
        results.append(" ".join(tmp))
    return results

corpus = remove_stop_words(corpus)
corpus[0:50]

['to all armys who were voting nonstop since yesterday thank you so much for your hard work rt quote',
 'me when d song plays on public',
 'minutes your last votes about  k replies on army this our countdown',
 'forget well trending hashtag at am kst when the music video drops',
 'theres about an hour left for voting keep using tags',
 'its been crucial week for chemocentryx inc heres what analysts have to say',
 'under not here',
 'please let us do job we are able',
 'what we want to ask exol in what ways does exo inspires with hashtag',
 'news channels not covering live what shame',
 'ellen meets yearold geography expert via this is funny intelligent you should watch this',
 'bts always breaks status',
 'nick gee',
 'thank you armys for voting remember that there round  of',
 'jongin hyung did you his you dont i didnt even know it was',
 'addiction party in sky mv teaser',
 'we want proof from mamta from where illegal bangladeshi rohingyas came in bengal',
 'this concept pretty rad',

In [7]:
def get_set(corpus):
    words = []
    for line in corpus:
        for word in line.split(' '):
            words.append(word)
    return set(words)

words = get_set(corpus)
words

{'',
 'cheating',
 'purchases',
 'totes',
 'june',
 'greenland',
 'gladness',
 'votes',
 'killings',
 'flashing',
 'investigated',
 'funds',
 'awardwapsi',
 'ajusshi',
 'supernatural',
 'jamming',
 'cutting',
 'virtue',
 'e',
 'sneaks',
 'lil',
 'hazard',
 'gift',
 'buys',
 'hujjaj',
 'ms',
 'ngyecatsha',
 'stayed',
 'peoples',
 'transexclusionary',
 'revolut',
 'quadruple',
 'nurses',
 'discography',
 'tournament',
 'dirty',
 'frank',
 'federation',
 'kochi',
 'pistol',
 'contagious',
 'by',
 'tomorow',
 'don',
 'nayapara',
 'harris',
 'swinney',
 'houtzager',
 'akpororo',
 'hump',
 'supporters',
 'spots',
 'beds',
 'favorite',
 'arrogant',
 'motto',
 'palmer',
 'italian',
 'sway',
 'lifelong',
 'ktsab',
 'weight',
 'didication',
 'ross',
 'brainwash',
 'incarceration',
 'lips',
 'intimate',
 'resolution',
 'lasuth',
 'gg',
 'succeed',
 'recorded',
 'bleeding',
 'ktigers',
 'cultural',
 'kitaro',
 'choosing',
 'fb',
 'ctto',
 'ozil',
 'airstrikes',
 'forget',
 'scandal',
 'limit',
 'l

In [8]:
len(words)

18175

# Skip-gram part

In [9]:
word2int = {}
for i, word in enumerate(words):
    word2int[word] = i
word2int

{'': 0,
 'cheating': 1,
 'purchases': 2,
 'totes': 3,
 'june': 4,
 'greenland': 5,
 'gladness': 6,
 'votes': 7,
 'killings': 8,
 'flashing': 9,
 'investigated': 10,
 'funds': 11,
 'awardwapsi': 12,
 'ajusshi': 13,
 'supernatural': 14,
 'jamming': 15,
 'cutting': 16,
 'virtue': 17,
 'e': 18,
 'sneaks': 19,
 'lil': 20,
 'hazard': 21,
 'gift': 22,
 'buys': 23,
 'hujjaj': 24,
 'ms': 25,
 'ngyecatsha': 26,
 'stayed': 27,
 'peoples': 28,
 'transexclusionary': 29,
 'revolut': 30,
 'quadruple': 31,
 'nurses': 32,
 'discography': 33,
 'tournament': 34,
 'dirty': 35,
 'frank': 36,
 'federation': 37,
 'kochi': 38,
 'pistol': 39,
 'contagious': 40,
 'by': 41,
 'tomorow': 42,
 'don': 43,
 'nayapara': 44,
 'harris': 45,
 'swinney': 46,
 'houtzager': 47,
 'akpororo': 48,
 'hump': 49,
 'supporters': 50,
 'spots': 51,
 'beds': 52,
 'favorite': 53,
 'arrogant': 54,
 'motto': 55,
 'palmer': 56,
 'italian': 57,
 'sway': 58,
 'lifelong': 59,
 'ktsab': 60,
 'weight': 61,
 'didication': 62,
 'ross': 63,
 'br

In [10]:
len(word2int)

18175

In [11]:
sentences = []
for sentence in corpus:
    sentences.append(sentence.split(' '))
    
sentences

[['to',
  'all',
  'armys',
  'who',
  'were',
  'voting',
  'nonstop',
  'since',
  'yesterday',
  'thank',
  'you',
  'so',
  'much',
  'for',
  'your',
  'hard',
  'work',
  'rt',
  'quote'],
 ['me', 'when', 'd', 'song', 'plays', 'on', 'public'],
 ['minutes',
  'your',
  'last',
  'votes',
  'about',
  '',
  'k',
  'replies',
  'on',
  'army',
  'this',
  'our',
  'countdown'],
 ['forget',
  'well',
  'trending',
  'hashtag',
  'at',
  'am',
  'kst',
  'when',
  'the',
  'music',
  'video',
  'drops'],
 ['theres',
  'about',
  'an',
  'hour',
  'left',
  'for',
  'voting',
  'keep',
  'using',
  'tags'],
 ['its',
  'been',
  'crucial',
  'week',
  'for',
  'chemocentryx',
  'inc',
  'heres',
  'what',
  'analysts',
  'have',
  'to',
  'say'],
 ['under', 'not', 'here'],
 ['please', 'let', 'us', 'do', 'job', 'we', 'are', 'able'],
 ['what',
  'we',
  'want',
  'to',
  'ask',
  'exol',
  'in',
  'what',
  'ways',
  'does',
  'exo',
  'inspires',
  'with',
  'hashtag'],
 ['news', 'channe

In [12]:
len(sentences)

15000

In [13]:
data = []
window_size = 2
for sentence in sentences:
    for i, target in enumerate(sentence):
        for word in sentence[max(0, i-window_size):min(len(sentence), i + window_size)+1]:
            r = randint(0, 20)
            if target != word and r == 3:
                data.append([target, word])

In [14]:
df = pd.DataFrame(data, columns=['input', 'label'])
df.head(10)

input    label
0      armys     were
1  yesterday      you
2        you     much
3       much       so
4          d       me
5      plays   public
6       your  minutes
7      votes     your
8          k         
9       army     this

In [15]:
df.shape

(30200, 2)

In [16]:
word2int

{'': 0,
 'cheating': 1,
 'purchases': 2,
 'totes': 3,
 'june': 4,
 'greenland': 5,
 'gladness': 6,
 'votes': 7,
 'killings': 8,
 'flashing': 9,
 'investigated': 10,
 'funds': 11,
 'awardwapsi': 12,
 'ajusshi': 13,
 'supernatural': 14,
 'jamming': 15,
 'cutting': 16,
 'virtue': 17,
 'e': 18,
 'sneaks': 19,
 'lil': 20,
 'hazard': 21,
 'gift': 22,
 'buys': 23,
 'hujjaj': 24,
 'ms': 25,
 'ngyecatsha': 26,
 'stayed': 27,
 'peoples': 28,
 'transexclusionary': 29,
 'revolut': 30,
 'quadruple': 31,
 'nurses': 32,
 'discography': 33,
 'tournament': 34,
 'dirty': 35,
 'frank': 36,
 'federation': 37,
 'kochi': 38,
 'pistol': 39,
 'contagious': 40,
 'by': 41,
 'tomorow': 42,
 'don': 43,
 'nayapara': 44,
 'harris': 45,
 'swinney': 46,
 'houtzager': 47,
 'akpororo': 48,
 'hump': 49,
 'supporters': 50,
 'spots': 51,
 'beds': 52,
 'favorite': 53,
 'arrogant': 54,
 'motto': 55,
 'palmer': 56,
 'italian': 57,
 'sway': 58,
 'lifelong': 59,
 'ktsab': 60,
 'weight': 61,
 'didication': 62,
 'ross': 63,
 'br

In [17]:
len(word2int)

18175

# PyTorch things

In [18]:
class Word2Vec(torch.nn.Module):
    def __init__(self, ONE_HOT_DIM, EMBEDDING_DIM):
        super(Word2Vec, self).__init__()
        self.linear1 = torch.nn.Linear(ONE_HOT_DIM, EMBEDDING_DIM)
        self.linear2 = torch.nn.Linear(EMBEDDING_DIM, ONE_HOT_DIM)
        self.softmax = torch.nn.Softmax(1)
        
    def forward(self, x):
        z1 = self.linear1(x)
        z2 = self.linear2(z1)
        y_pred = self.softmax(z2)
        return y_pred

In [19]:
ONE_HOT_DIM = len(words)

# convert numbers to one hot vectors
def to_one_hot_encoding(index):
    one_hot_encoding = np.zeros(ONE_HOT_DIM)
    one_hot_encoding[index] = 1
    return one_hot_encoding

X = [] # input word
Y = [] # target word

for x, y in zip(df['input'], df['label']):
    X.append(to_one_hot_encoding(word2int[x]))
    Y.append(to_one_hot_encoding(word2int[y]))

In [20]:
X_train = np.float32(X)
Y_train = np.float32(Y)

X_train = torch.from_numpy(X_train)
Y_train = torch.from_numpy(Y_train)

print(X_train.shape)
print(Y_train.shape)

print(X_train[0])
print(Y_train[0])

EMBEDDING_DIM = 5

# model = torch.nn.Sequential(
#     torch.nn.Linear(ONE_HOT_DIM, EMBEDDING_DIM),
#     torch.nn.Linear(EMBEDDING_DIM, ONE_HOT_DIM),
#     torch.nn.Softmax()
# )

model = Word2Vec(ONE_HOT_DIM, EMBEDDING_DIM)

loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 0.005

torch.Size([30200, 18175])
torch.Size([30200, 18175])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])


In [21]:
for t in range(1):
    
    y_pred = model(X_train)
    loss = loss_fn(y_pred, Y_train)
    print(t, loss.item())
    
    model.zero_grad()
    
    loss.backward()
    
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

RuntimeError: $ Torch: not enough memory: you tried to allocate 2GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:201

In [20]:
print(model.linear1.weight.shape)

torch.Size([20, 403])


In [21]:
vectors = model.linear1.weight.detach().numpy().T
vectors

array([[-0.17036709,  0.09948716, -0.64546955, ..., -1.2370772 ,
         0.03468226,  0.25772542],
       [ 1.8442827 , -1.5516379 ,  0.58389235, ..., -0.01800065,
         1.446184  , -1.247507  ],
       [-0.59695613,  0.3260607 ,  0.41158122, ..., -0.5817607 ,
         0.1475991 ,  0.39548483],
       ...,
       [ 0.21131268, -0.36480552,  0.1440691 , ..., -0.45624775,
         0.40841144,  0.17381735],
       [ 1.7021484 , -0.92932385, -0.41065198, ...,  0.47364876,
        -0.58841   ,  0.4570295 ],
       [ 0.02214304,  0.15715274,  0.77689075, ...,  0.10169718,
         0.6218604 , -0.5947838 ]], dtype=float32)

## Word vector in table

In [22]:
w2v_df = pd.DataFrame(vectors, columns=['x1', 'x2'])
w2v_df['word'] = words
w2_df = w2v_df[['word', 'x1', 'x2']]
w2v_df

ValueError: Shape of passed values is (20, 403), indices imply (2, 403)

In [ ]:
fig, ax = plt.subplots()

for word, x1, x2 in zip(w2v_df['word'], w2v_df['x1'], w2v_df['x2']):
    ax.annotate(word, (x1, x2))

PADDING = 1.0
x_axis_min = np.amin(vectors, axis=0)[0] - PADDING
y_axis_min = np.amin(vectors, axis=0)[1] - PADDING
x_axis_max = np.amax(vectors, axis=0)[0] + PADDING
y_axis_max = np.amax(vectors, axis=0)[1] + PADDING

plt.xlim(x_axis_min, x_axis_max)
plt.ylim(y_axis_min, y_axis_max)
plt.rcParams["figure.figsize"] = (100, 100)

plt.show()